### ISSUE TITLE
Not all PS_APP_HOMEs have cscblbld.bat

### ISSUE THREAD

**Issue by iversond** [umaritimus/pscobol#1]
When trying to build PS_APP_HOME on Finance or HR, the invoke-cobolcompile command fails. The file `cscblbld.bat` doesn't exist for those applications (guessing this is Campus-specific?). Instead, we just use the main `PS_HOME\setup\cblbld.bat` command but pass in `PS_APP_HOME` as a parameter.

Thoughts on adding a flag for Campus customers so that we can use this with no-Campus applications?

https://github.com/umaritimus/pscobol/blob/master/files/pscobol.psm1#L223

**Comment by iversond** [comment]
Wait, I might be dumb. That's an if statement and I glossed over the other condition...

**Comment by umaritimus** [comment]
@iversond - Wait, are you just looking at the source code or actually running it through puppet?

**Comment by umaritimus** [comment]
confirmed non-issue
